### ISSUE TITLE
Whispers - Invalid control character

### ISSUE THREAD

**Issue by cosad3s** [cosad3s/postleaks#9]
Some result cannot be parsed by whisper.

Example

```bash
Traceback (most recent call last):
  File "/home/seb/.local/lib/python3.11/site-packages/whispers/plugins/json.py", line 27, in pairs
    document = json.loads(document)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 29 column 15 (char 928)
```

*(Test case internally kept for the moment)*

**Comment by cosad3s** [comment]
Cannot reproduce now.
